### ISSUE TITLE
[Bug]: crash when right click on any block

### ISSUE THREAD

**Issue by TheRanker** [ixDarkLorD/UltimineAddition#11]
### Describe the Bug

server or single player crashes when right click any block... villagers work but blocks crashes to desktop.

see attached crash log. 

### To Reproduce

1. have latest versoin of ultimine and ultimine additions.
2. load up a world.. new or old
3.right click any block
4.instant crash to desktop.

### Crash Report or Log

https://gist.github.com/TheRanker/72898a43f1574302fb10832814bce288

### OS

windows 10

### Minecraft Version

1.20.1

### ModLoader

Forge

### Mod Version

ultimine_addition-forge-1.20.1-v1.2.0a-release.jar

**Comment by ixDarkLorD** [comment]
Thank you for reporting! ✨
Checkout the new update (1.2.0b)
