### ISSUE TITLE
[Bug]: Incompatibility with DefaultSettings

### ISSUE THREAD

**Issue by PT400C** [ixDarkLorD/UltimineAddition#12]
### Describe the Bug

FTB Ultimine Addition deviates from the widely accepted format for mod keybinds (`key_key.NAME:key.KEY`) by introducing a second colon in the key's name. DefaultSettings currently doesn't expect that behavior and refuses to handle those keys properly.

While we'll publish a fix on our end soon, I suggest that you change the keybind format from `key_key.ultimine_addition:NAME:key.KEY` to `key_key.NAME:key.KEY` for compatiblity reasons.

Reference: https://github.com/Jomcraft-Network/DefaultSettings/issues/18

### To Reproduce

1. Install FTB Ultimine Addition and DefaultSettings in Forge/Fabric 1.20.1
2. Execute `/ds save`
3. Inspect the error log

### Crash Report or Log

https://pastebin.com/bjk5CZTY

### OS

Windows 10

### Minecraft Version

1.20.1

### ModLoader

Forge

### Mod Version

v1.2.0b RELEASE

**Comment by ixDarkLorD** [comment]
I solved the issue in the next update. (v1.2.1) 🤍
