### ISSUE TITLE
[Bug]: Chunks resetting on server load

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#16]
### Describe the Bug

Hello, I have a self made modpack and have been setting up spawn before players join. Chunks sometimes randomly seem to reset and regenerate on server boot. I have looked in the logs from last time it happened, and found the below, mentioning Architectury and Ultimine Additions. I was wondeirng if someone could look at this and see if they can discern the issue? Maybe its an issue with one or the other mod, or both together? Please note I have already created a whole new world so I know its the not the world itself being corrupted.

This is MC 1.19.2, Forge 43.3.7 , Architectury API v6.5.85, Ultimine Additions 1.2.2

Here is the chunk error from log file

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/48ecd31f-cb48-4a96-abc6-67565f5fff1f)

I have also attached the full log file.

[2024-02-04-6_2.log](https://github.com/ixDarkLorD/UltimineAddition/files/14166963/2024-02-04-6_2.log)

### To Reproduce

Start server - sometimes it will fail to load chunks and they will regenerate

### Crash Report or Log

https://github.com/ixDarkLorD/UltimineAddition/files/14166963/2024-02-04-6_2.log

### OS

Serer is on Ubuntu 20.04 LTS

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.2.2

**Comment by ixDarkLorD** [comment]
I fixed it.
Check out the new update v1.2.3

**Comment by sprocketaudio** [comment]
Thanks so much, I'll test it now :)
