### ISSUE TITLE
[Bug]: Mining blocks isnt registered when Skills record is in Curios slot

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#17]
### Describe the Bug

As per title - tested with my mining coal quest. If I place the Skills Record in my inventory it records my actions fine. If I place it in curios slot, it doesnt count mined blocks anymore.

v1.19.2-1.2.3
Curious v1.19.2-5.1.6.1

Pictures to show steps. it stays ion 14 mined.

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/e112203c-ec5b-4669-81f5-e4d7bc951889)

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/adfdbdb8-8ae2-4db6-b523-28d5255f68c4)

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/e6891a3f-8dd8-4e57-a23c-54c4cfb1c838)

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/299ee97a-61e6-4413-8617-372127df6896)

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/b2d969b2-7308-4b2f-92db-902fb02596c8)

### To Reproduce

1. Place Skills record in Curios slot
2. Mine quest block
3. It won't be recognised

### OS

Ubuntu

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.2.3

**Comment by ixDarkLorD** [comment]
I'm glad that you're helping me out by submitting the issues
I truly appreciate it.
Thank you. 🤍✨

It will be fixed in the upcoming update v1.2.4

**Comment by sprocketaudio** [comment]
Haha no problem - its as cool mod so thank you :)
