### ISSUE TITLE
[Feature]: Allow setting to enable per tool full unlock

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#18]
### What feature do you want to see in the upcoming releases?

Using this in a modpack has been fun, but people have been wondering why when they 'Master' a tool, they have to master every other tool to unlock ultimine for that specific tool.

Suggestion to add a config option to enable per tool ultimine unlock once u get the 'Master' certificate for that one tool.

**Comment by ixDarkLorD** [comment]
I'm happy to hear that you are enjoying the mod.
I was wondering why I didn't think of that before. 😅

But before I begin working on it, I have a question. When a player masters a tool, should I activate the ultimine ability for that particular tool only if the player has the card in their inventory?

**Comment by sprocketaudio** [comment]
It depends on your code and how u want to implement it I guess.. my non coder brain says if the config was enabled for this, you could right click 'use' a master card (like u can the certificate currently) to unlock that tools ultimine permanently, loosing the card in the process. Once u ahve used all 4 you wont need to craft the certificate any more!

If this is hard to do due to how u have implemented it, then I can also imagine having a Mastered card in your inv (or still in the skills record, which of course could also be in curios slot) could give you unlimited-time Mine Go lv 3 potion for that skill. This way you could still get the player to craft the final certificate once they have all 4?

**Comment by ixDarkLorD** [comment]
I released an update. ✨
Thank you for suggesting the ideas
I've chosen the second one to avoid making the Miner Certificate useless
The config file will have an option to toggle it ON/OFF.

**Comment by sprocketaudio** [comment]
awesome! Did you release it though? haha I can't see it on curse?

**Comment by ixDarkLorD** [comment]
I did actually lol
I don't know why it took so much time to get approved

**Comment by sprocketaudio** [comment]
Not sure if this is a bug or just how ultimine works, but you can use this now to ultimine any block with one tool (albeit a little slower than the correct tool)

**Comment by ixDarkLorD** [comment]
Unfortunately, this is how Ultimine operates.
I had attempted to encounter their tool-checking methods before, but it didn't yield positive results.
