### ISSUE TITLE
[Bug]: loss of skill on death

### ISSUE THREAD

**Issue by Monster-Zer0** [ixDarkLorD/UltimineAddition#2]
### Describe the Bug

if you die after getting the skill, you lose the skill completely

### To Reproduce

1.make a miner cert
2.complete the 400 ores
3.apply to weapon
4.die
5. lose skill

### OS

windows 11

### Minecraft Version

1.18.2

### ModLoader

Fabric

### Mod Version

0.1.0-beta

**Comment by ixDarkLorD** [comment]
Thank you for addressing the issue 🤍
It got fixed in the new update. (0.1.0a)

**Comment by BunkerBaerIGER** [comment]
Same error at version 1.0.2a

**Comment by ixDarkLorD** [comment]
> Same error at version 1.0.2a Forge 1.19.2

Can you please describe a little more how it happened?
Like it happened in a Singleplayer or a Server?

**Comment by BunkerBaerIGER** [comment]
i opened a new issue
