### ISSUE TITLE
[Bug]: 'Paper' and the skill cards are both seemingly counted as the 'same' item in the certificate crafting!

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#21]
### Describe the Bug

'Paper' and the skill cards are both seemingly counted as the 'same' item in the certificate crafting!

### To Reproduce

1. Install just this mod and JEI for testing
2. Load new world
3. Craft the Mining certificate with 5 paper!
4. Profit

### Catch the bug In Action!

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/68d077d1-1c9a-4b8b-b8e6-e6d508ff4eaa)

### OS

Ubuntu

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.19.2-1.3.0

**Comment by ixDarkLorD** [comment]
I've resolved the issue. The upcoming update will ensure that it is functioning correctly.
