### ISSUE TITLE
[Bug]: Tools other than default do not count towards progress

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#22]
### Describe the Bug

Tools like copper pickaxe (or any other non default mining tools) do not seem to count towards progress of your missions

### To Reproduce

1. 
2.
3.
4.

### OS

Ubuntu

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.19.2-1.3.0

**Comment by ixDarkLorD** [comment]
From which mod is the copper pickaxe?

**Comment by sprocketaudio** [comment]
create stuff and additions but it also doesnt work withy tools from stalwart dungeons and maybe more as jsut going off user reports.

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/d67bfe45-03b5-4f64-88a0-6ed4fd2ecd20)

![image](https://github.com/ixDarkLorD/UltimineAddition/assets/13222732/bd312fc8-9356-4cc9-b31e-6b53b31b4570)

**Comment by ixDarkLorD** [comment]
Great! I've identified and resolved the issue. 
It'll be fixed in the upcoming update.

Thank you for helping ✨🙏
