### ISSUE TITLE
[Bug]: On Win11 Home v23H2 the latest 1.19.2 version reports a trojan!

### ISSUE THREAD

**Issue by sprocketaudio** [ixDarkLorD/UltimineAddition#23]
### Describe the Bug

On Win11 Home v23H2 the latest 1.19.2 - 1.3.2 version reports a trojan! - A player has reported this to me. Doesnt happen when downloading the 1.20 version and also doesnt happen for the previous version release 1.3.1.

I also do not get this issue on win10! - Prob a false positive but thought I'd report it.

### To Reproduce

1.
2.
3.
4.

### OS

Windows 11

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.3.2

**Comment by ixDarkLorD** [comment]
It didn't happen to me either so... I think Microsoft Defender may be confused xD
But anyway, rest assured that Curseforge scans all mods for malware when they are uploaded to the website. Therefore, there is no need to worry about any false alerts.

Also if it happened to you let me know I'm here to help. ✨
