### ISSUE TITLE
[Bug]1.21 NEOFORGE : Crash on Righclick on block with Axe

### ISSUE THREAD

**Issue by MathisSkate** [ixDarkLorD/UltimineAddition#26]
### Describe the Bug

When you rightclick on a block with an axe, the game crash

### To Reproduce

1. Download the latest version of FTB Ultimine additions
2. Use Neoforge latest (21.1.64)
3. Take a Axe
4. Rightclick on a block

### Crash Report or Log

https://hastebin.com/share/uturudodel.bash

### OS

Windows 11

### Minecraft Version

1.20.1

### ModLoader

Forge

### Mod Version

neoforge-v1.0.0

**Comment by ixDarkLorD** [comment]
I've resolved the issue in the latest update v1.0.1 ✨
Thank you for submitting a ticket! 🙏❤️
