### ISSUE TITLE
[Bug]: Quest not working when using Paxel

### ISSUE THREAD

**Issue by Switch-Back18** [ixDarkLorD/UltimineAddition#27]
### Describe the Bug

When we breaks blocks with Paxel the mod not registered the block that we breaks

### To Reproduce

1. Install Ultimine Addition
2. Install a mods that's add Paxel
3. Try to break a block (Wood, Ores, ore shovel blocks)
4. The block is not counted in the quest

### OS

Windows 11

### Minecraft Version

1.21.1

### ModLoader

NeoForge

### Mod Version

1.0.1

**Comment by ixDarkLorD** [comment]
I'll look into it.
Can you tell me the paxel you used from which mod?

**Comment by MathisSkate** [comment]
In my pack i use packel from Mekanism Tools, Mystical Aggradditions and Gobber2

**Comment by Switch-Back18** [comment]
There is AIOT from Actually Additions too

**Comment by ixDarkLorD** [comment]
I apologize for taking so much time.
This will be fixed in the next update ❤️
