### ISSUE TITLE
[Feature]: Shape Limits

### ISSUE THREAD

**Issue by penturt** [ixDarkLorD/UltimineAddition#28]
### What feature do you want to see in the upcoming releases?

I like what this mod does, i think some mining shapes might be a bit more overpowered then others, i would like to request a way  to remove/limit which mining options/shapes are available to a players? I'm not trying to exclude mineable blocks, but rather the options for shapes the player can use... for example i only want the player to be able to use shapeless and small tunnel options...

**Comment by ixDarkLorD** [comment]
Thank you for reporting! ✨
This feature will be added in the next update ❤️

**Comment by penturt** [comment]
awesome, thank you... i'm guessing its not the 1.21 - 1.21.1 | v1.0.2 release, right?

**Comment by ixDarkLorD** [comment]
This is the new version. Just update the mod, and you can use the new feature. ✨
The settings can be modified in the config file at "ultimine_addition/common-config.toml."

- **🗒️ Ensure that this setting is adjusted identically on both the Client and Server.**

![image](https://github.com/user-attachments/assets/6ef7c36d-c003-4e6a-b00f-7aa374bfaae0)
