### ISSUE TITLE
[Bug]: Game crash after crafting Mining card [MC 1.21.1 - NeoForge 21.1.91]

### ISSUE THREAD

**Issue by BelleBernice** [ixDarkLorD/UltimineAddition#29]
### Describe the Bug

Hello, i added your mod to my ATM 10 instance, but after crafting the Pickaxe Card with a Stone Pickaxe and pressing Esc, the world crashes on save. 

Next i tested it on a clean instance of ATM 10 and still the same problem.
After that i tested it on a clean instance of Minecraft for 1.21.1 and NeoForge v21.1.91 (because it's the same as ATM 10) and this time i crafted the Hoe Card with a Stone Hoe. Game crash with the same problem.

In conclusion, all the tests have the same results, the game crashes after crafting ANY mining card from the mod.

### To Reproduce

1. Install a new instance of Minecraft v1.21.1 - NeoForge v21.1.91
2. Create a new world
3. Craft a mining card with a Stone tool
4. Press Esc to force the world save

### Crash Report or Log

https://mclo.gs/oqF2W2X

### OS

Windows 11

### Minecraft Version

1.21.1

### ModLoader

NeoForge

### Mod Version

https://www.curseforge.com/minecraft/mc-mods/ultimine-addition/files/5769592

**Comment by ixDarkLorD** [comment]
Thank you for submitting your ticket. I'll start working on it.

**Comment by ixDarkLorD** [comment]
This issue will be fixed in the next update ❤️
