### ISSUE TITLE
[Bug]: Cant Join Server with mod installed on both sides.

### ISSUE THREAD

**Issue by Fundryi** [ixDarkLorD/UltimineAddition#5]
### Describe the Bug

When trying to join the server I get this error:
![image](https://github.com/ixDarkLorD/UltimineAddition/assets/19733372/e2087fd9-2e32-4cf1-9b94-adfd7b86bc0a)

It works fine as soon as I remove the mod from the server and disable it on the Client.

### To Reproduce

1. Start modpack: https://www.curseforge.com/minecraft/modpacks/nplx-vanilla
2. Try to join server
3. Error

Also its on MC 1.20.2 Latest Forge 47.2.1 (cant choose 1.20 below)

### OS

Win 11

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.20.1-v0.1.0-beta

**Comment by Fundryi** [comment]
Disabled the mod on the Server and still had it enabled on the Client and was able to join the server without issues.

**Comment by ixDarkLorD** [comment]
I'm sorry to hear that. I fixed it in the new update v0.1.1
