### ISSUE TITLE
[Bug]: Error on /reload

### ISSUE THREAD

**Issue by BunkerBaerIGER** [ixDarkLorD/UltimineAddition#6]
### Describe the Bug

If I try to use the /reload command I get the following error: "Reload failed; keeping old data"

### To Reproduce

Use /reload in game

### Crash Report or Log

https://pastebin.com/KWHERYj5

### OS

Windows 11

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

All versions

**Comment by ixDarkLorD** [comment]
I fixed it in the new update v1.0.2a 🤍
