### ISSUE TITLE
[Bug]: Lose Ultimine after death

### ISSUE THREAD

**Issue by BunkerBaerIGER** [ixDarkLorD/UltimineAddition#7]
### Describe the Bug

Using Miners Certificate -> unlocks Ultimine
Player died -> Ultimine locked

On singleplayer and multiplayer game

### To Reproduce

1. Use Miners Certificate
2. Player died

### OS

Windows 11

### Minecraft Version

1.19.2

### ModLoader

Forge

### Mod Version

1.0.2a

**Comment by ixDarkLorD** [comment]
Checkout the new update v1.1.0 🤍
