### ISSUE TITLE
[Bug]: Block break doesn't count for skills record

### ISSUE THREAD

**Issue by Azelza** [ixDarkLorD/UltimineAddition#8]
### Describe the Bug

I'm trying to progress on Skills Record but the challenges not count my block breaks

### To Reproduce

1.craft skills record
2.put mining skill card, pen and paper
3.break the challenge blocks
4.progress bar not moving

### OS

windows 11

### Minecraft Version

1.20.1

### ModLoader

Forge

### Mod Version

0.1.1a-beta

**Comment by ixDarkLorD** [comment]
Does this happen in Singleplayer or Multiplayer?
And is the block you are trying to break placed by a player or block placer thing?
And can you demonstrate this issue on a video? Because on my side, I couldn't recreate this.

**Comment by Azelza** [comment]
I'm playing on singleplayer https://streamable.com/hqiht9

**Comment by ixDarkLorD** [comment]
Oh, I see. The mod is supposed to work like this! If the required block is placed by a Player or Block Placer from any mod, It will not count toward the challenge.
For now. If you don't like it, there is a way to bypass this system! You can add the blocks you desire in a tag named "ultimine_addition:deny_is_placed_by_entity" through Datapack.

P.S. I'm about to release a new update for the mod that includes an ON/OFF option in the config for this matter.
