### ISSUE TITLE
[Bug]: If you break blocks with Silent Gear tools, it wont count as block break

### ISSUE THREAD

**Issue by Azelza** [ixDarkLorD/UltimineAddition#9]
### Describe the Bug

 If you break blocks with Silent Gear tools, it wont count as block break

### To Reproduce

1.Craft a silent gear pickaxe
2.Break some blocks with silent gear pickaxe for skill card progression
3.Progression wont count

### OS

windows 11

### Minecraft Version

1.20.1

### ModLoader

Forge

### Mod Version

1.1.0

**Comment by ixDarkLorD** [comment]
I'm sorry to hear that, I fixed it! Check out the new update. ❤️
